/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/halo/engine */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */





/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* HaloPing(void);
extern char* HaloVersion(void);
extern char* HaloGenerateIdentity(void);

// restores identity from hex-encoded ed25519 priv (64 bytes hex = 128 chars) +
// X25519 priv (32 bytes hex = 64 chars). recomputes pubkeys + halo_id.
extern char* HaloRestoreIdentity(char* cEdPriv, char* cXPriv);
extern char* HaloMyId(void);
extern char* HaloMyEdPubkey(void);
extern char* HaloMyXPubkey(void);

// exports private keys so the dart side can persist them encrypted.
// only call this once after generation; do NOT log or transmit.
extern char* HaloMyEdPrivkey(void);
extern char* HaloMyXPrivkey(void);
extern char* HaloIdFromPubkey(char* cHex);
extern char* HaloEncryptFor(char* cPeerPub, char* cPlain);
extern char* HaloDecryptFrom(char* cPeerPub, char* cB64);
extern char* HaloStartListener(char* cDataDir);
extern char* HaloGetStatus(void);
extern char* HaloDrainInbox(void);
extern char* HaloSendTo(char* cAddr, char* cMsg);
extern char* HaloNostrInit(char* cRelaysCSV);
extern char* HaloNostrSend(char* cPeerXPubHex, char* cMsg);
extern char* HaloNostrSubscribe(char* cPeerXPubHex);
extern char* HaloNostrPoll(void);

// posts a wake-up trigger to the peer's ntfy endpoint via tor. fire-and-
// forget from dart's perspective. message body is a fixed string; ntfy
// only cares that *something* arrived to wake subscribers.
extern char* HaloNtfyPing(char* cEndpoint);

#ifdef __cplusplus
}
#endif
