/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/halo/engine */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */











/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void HaloSetDebug(int on);
extern char* HaloPing(void);
extern char* HaloVersion(void);
extern char* HaloGenerateIdentity(void);

// restores identity from hex-encoded ed25519 priv (64 bytes hex = 128 chars) +
// X25519 priv (32 bytes hex = 64 chars). recomputes pubkeys + halo_id.
//
extern char* HaloRestoreIdentity(char* cEdPriv, char* cXPriv);
extern char* HaloMyId(void);
extern char* HaloMyEdPubkey(void);
extern char* HaloMyXPubkey(void);

// exports private keys so the dart side can persist them encrypted.
// only call this once after generation; do NOT log or transmit.
//
extern char* HaloMyEdPrivkey(void);
extern char* HaloMyXPrivkey(void);
extern char* HaloIdFromPubkey(char* cHex);
extern char* HaloEncryptFor(char* cPeerPub, char* cPlain);
extern char* HaloDecryptFrom(char* cPeerPub, char* cB64);
extern char* HaloStartListener(char* cDataDir);
extern void HaloShutdown(void);
extern char* HaloGetStatus(void);
extern char* HaloDrainInbox(void);
extern char* HaloSendTo(char* cAddr, char* cMsg);

// derives the 3-word BIP-39 halo id from an ed25519 public key hex string.
// used during back-pair when a stranger's first message arrives and we need
// to compute their halo id from the identity key in the libsignal envelope.
//
extern char* HaloIdFromEdPub(char* cHexPub);

// encrypts a UTF-8 plaintext payload (typically a JSON blob containing
// the user's identity keys + db + prefs) with a passphrase using scrypt
// (32768 / 8 / 1) + AES-256-GCM. returns "halo-backup:v1:" + base64
// (salt || nonce || ciphertext+tag). returns "error: ..." on failure.
//
extern char* HaloEncryptBackup(char* cPlain, char* cPassphrase);

// inverse of HaloEncryptBackup. returns plaintext on success or
// "error: wrong passphrase or corrupt" on auth failure.
//
extern char* HaloDecryptBackup(char* cBlob, char* cPassphrase);

// takes newline separated bridge lines and whether to use them. the caller is
// expected to restart tor afterwards; changing this mid-session does nothing
// on its own, because tor reads the config once at startup.
//
extern char* HaloSetBridges(char* cLines, int on);

// what the ui needs: whether bridges are on, how many are configured, and
// whether the local transport is actually up.
//
// bounce tor so it picks up a config change. bridges are the only reason to
// call this - tor reads its arguments once and never again, so toggling them
// without a restart looks like the feature silently not working.
//
extern char* HaloRestartTor(void);
extern char* HaloBridgeState(void);

//
// is this handle free? returns "free", "taken", or an error string.
extern char* HaloHandleCheck(char* cHandle);

//
// claim a handle for an invite. the signature is over the handle alone, made
// with the identity key, so the registry can check the claimer is the person
// the invite describes.
extern char* HaloHandleClaim(char* cHandle, char* cInvite, char* cBio);

//
// give it back. the same signature proves it was yours to release.
extern char* HaloHandleRelease(char* cHandle);

// ask for a captcha. returns "ok|<base64 png>|<challenge>" or "error: ...".
// the challenge is opaque and must be handed back with the answer; it carries
// a signed timestamp and dies after thirty minutes.
//
extern char* HaloMoatFetch(void);

// send the answer back. returns "ok|<bridge lines separated by newline>",
// "wrong" if the captcha was not solved, or "error: ...".
//
extern char* HaloMoatSolve(char* cChallenge, char* cSolution);
extern char* HaloNostrInit(char* cRelaysCSV);
extern char* HaloNostrSend(char* cPeerXPubHex, char* cMsg);
extern char* HaloNostrSubscribe(char* cPeerXPubHex);

// the public half of our first-contact address. goes in the invite so a
// stranger can reach us before either side knows the other's key.
//
extern char* HaloFirstContactPk(int counter);

// watch our own first-contact address. unlike every other subscription this
// needs no contacts, which is the whole point: a fresh install with an empty
// roster can still be reached.
//
extern char* HaloNostrSubscribeFirstContact(int counter);

// introduce ourselves to someone who has never heard of us. the seal is
// signed with our usual per-conversation key, so once they know us the normal
// verification applies to everything after this.
//
extern char* HaloNostrSendFirstContact(char* cPeerXPubHex, char* cFcPk, char* cMsg);
extern char* HaloNostrPoll(void);

// posts a wake-up trigger to the peer's ntfy endpoint via tor. fire-and-
// forget from dart's perspective. message body is a fixed string; ntfy
// only cares that *something* arrived to wake subscribers.
//
extern char* HaloNtfyPing(char* cEndpoint);

// fetch a url over the tor http client and return the html body (capped).
// used for sender-side link previews so the receiver never has to fetch and
// leak their ip. best-effort: returns "error: ..." on any failure, caller skips.
//
extern char* HaloTorGet(char* cUrl);

// POST json over tor, returning the response body. used for the badge
// service (creating a donation invoice) so the donor's ip never touches
// anything. any non-2xx comes back as "error: ..." for the caller to skip.
//
extern char* HaloTorPost(char* cUrl, char* cBody);

// GET over tor that keeps the body for ANY 2xx - the badge service answers
// 202 while a payment is still pending, which HaloTorGet would reject.
//
extern char* HaloTorGetJSON(char* cUrl);

// like HaloTorGet but returns the body base64-encoded, for binary content
// (link-preview images). fetched over tor so the receiver never loads the
// image from the origin and leaks their ip. capped larger than html.
//
extern char* HaloTorGetB64(char* cUrl);

// put an invite at the address the code names. encrypted to the derived key,
// so it is readable by whoever has the code and nobody else, and stamped to
// expire in ten minutes.
//
extern char* HaloPairCodePublish(char* cCode, char* cPayload);

// look for an invite at the address the code names. returns the payload, or
// "empty" when nothing is there yet - the caller polls, because the other
// person may not have pressed share.
//
extern char* HaloPairCodeFetch(char* cCode);

// private, balanced or fast. anything else is treated as private, because a
// typo must never quietly drop someone out of tor.
//
extern char* HaloSetTransportMode(char* cMode);
extern char* HaloTransportMode(void);
extern char* HaloTransportState(void);

#ifdef __cplusplus
}
#endif
